version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build_windows:

  build_test:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn build
workflows:
  version: 2
  build:
    jobs:
      - build_test:
          filters:
            branches:
              only: main
