version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build_test:
    macos:
      xcode: '12.4.0'
    steps:
      - checkout
      - run: yarn && yarn build
  build_macos:
    macos:
      xcode: '12.4.0'
    steps:
      - checkout
      - run: yarn && yarn build
      - run: cd dist && mv BGMs*.dmg "bgms-remote-control-macOS.dmg"
      - store_artifacts:
          path: dist/bgms-remote-control-macOS.dmg
      - persist_to_workspace:
          root: .
          paths:
            - dist/bgms-remote-control-macOS.dmg
workflows:
  version: 2
  build:
    jobs:
      - build_test:
          filters:
            branches:
              only: main
